//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAdmissionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AdmissionTransactions
    {
        public int admission_ID { get; set; }
        public Nullable<int> course_ID { get; set; }
        public Nullable<double> degreee_marks { get; set; }
        public Nullable<double> puc_marks { get; set; }
        public Nullable<double> sslc_marks { get; set; }
        public string document_path { get; set; }
        public string student_name { get; set; }
        public string student_father_name { get; set; }
        public Nullable<System.DateTime> student_dob { get; set; }
        public string student_gender { get; set; }
        public string student_address { get; set; }
        public string admission_status { get; set; }
        public Nullable<int> adhar_number { get; set; }
        public string student_religion { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual tbl_courses tbl_courses { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
