//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAdmissionSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_courses
    {
        public int Course_ID { get; set; }
        public Nullable<int> Dept_ID { get; set; }
        public string Course_Name { get; set; }
        public Nullable<int> Course_duration { get; set; }
        public string Course_substream { get; set; }
        public Nullable<double> Course_Fees { get; set; }
    
        public virtual tbl_department tbl_department { get; set; }
    }
}
